# Generated by Django 4.2 on 2025-09-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('file_pdf', models.FileField(upload_to='surat/')),
                ('waktu_pengarsipan', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arsip_surat.kategori', verbose_name='Kategori Surat')),
            ],
        ),
    ]
